baseURL = 'https://blog.yenslife.top/'
languageCode = 'en-us'
title = 'æµ·ç‹¸å¤§å¸«éƒ¨è½æ ¼'
theme = 'hugo-theme-stack'

[languages]
   [languages.en]
     contentDir = 'content/en'
     languageName = 'English'
     weight = 10
     title = "Yenslife Blog"
     # subtitle = "This is a subtitle"
   [languages.zh-tw]
     contentDir = 'content/zh-tw'
     languageName = 'å°ç£æ­£é«”'
     weight = 20
     title = "æµ·ç‹¸å¤§å¸«éƒ¨è½æ ¼"
     # subtitle = ""

[params]
description = "æ¸¬è©¦ç”¨çš„ description"
mainSections = [ "post" ]

[params.sidebar]
compact = false
emoji = "ğŸ¦«"
avatar = { enabled = true, src = "img/avatar.jpg", local = true}

[params.widgets]
[[params.widgets.homepage]]
type = "search"
[[params.widgets.homepage]]
type = "tag-cloud"
[[params.widgets.homepage]]
type = "categories"

[[params.widgets.page]]
type = "search"
[[params.widgets.page]]
type = "toc"
[[params.widgets.page]]
type = "categories"
[[params.widgets.page]]
type = "tag-cloud"

[params.article]
license = { enabled = true }
readingTime = true
