baseURL = 'https://blog.yenslife.top/'
languageCode = 'en-us'
title = 'æµ·ç‹¸å¤§å¸«éƒ¨è½æ ¼'
theme = 'hugo-theme-stack'

[languages]
   [languages.en]
     contentDir = 'content/en'
     languageName = 'English'
     weight = 10
   [languages.zh-tw]
     contentDir = 'content/zh-tw'
     languageName = 'å°ç£æ­£é«”'
     weight = 20

[params]
description = "æ¸¬è©¦ç”¨çš„ description"
mainSections = [ "post" ]

[params.sidebar]
compact = false
emoji = "ğŸš¬"
subtitle = "é€™æ˜¯ä¸€å€‹ subtitle"
# TODO: Add Avatar url

[params.widgets]
[[params.widgets.homepage]]
type = "search"
# [params.widgets.homepage.params]
[[params.widgets.homepage]]
type = "tag-cloud"

[[params.widgets.page]]
type = "search"
[[params.widgets.page]]
type = "toc"
[[params.widgets.page]]
type = "categories"
[[params.widgets.page]]
type = "tag-cloud"

