baseURL = 'https://blog.yenslife.top/'
languageCode = 'en-us'
title = 'æµ·ç‹¸å¤§å¸«éƒ¨è½æ ¼'
theme = 'hugo-theme-stack'
DefaultContentLanguage = 'zh-tw'

[languages]
   [languages.en]
     contentDir = 'content/en'
     languageName = 'English'
     weight = 20
     title = "Yenslife Blog"
     # subtitle = "This is a subtitle"
   [languages.zh-tw]
     contentDir = 'content/zh-tw'
     languageName = 'å°ç£æ­£é«”'
     weight = 10
     title = "æµ·ç‹¸å¤§å¸«éƒ¨è½æ ¼"
     # subtitle = ""

[params]
description = "æ¸¬è©¦ç”¨çš„ description"
mainSections = [ "post" ]

# å…è¨±åœ¨ Markdown ä¸­ä½¿ç”¨ HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "default"
    lineNos = false
    lineNumbersInTable = false
    noClasses = false # ä¸èƒ½è¨­ç‚º false æ‰èƒ½æ”¹ä¸€äº› code block çš„æ¨£å¼

[params.sidebar]
compact = false
emoji = "ğŸ¦«"
avatar = { enabled = true, src = "img/avatar.jpg", local = true}

[params.widgets]
[[params.widgets.homepage]]
type = "search"
[[params.widgets.homepage]]
type = "tag-cloud"
[[params.widgets.homepage]]
type = "categories"

[[params.widgets.page]]
type = "search"
[[params.widgets.page]]
type = "toc"
[[params.widgets.page]]
type = "categories"
[[params.widgets.page]]
type = "tag-cloud"

[params.article]
license = { enabled = true }
readingTime = true

[params.footer]
since = 2025
# customText = "æ–°ç¶²ç«™"

# ç•™è¨€
[params.comments]
enabled = true
provider = "giscus"

[params.comments.giscus]
repo = "yenslife/blog.yenslife.top"
repoID = ""
category = ""
categoryID = ""
mapping = ""
strict = true
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0
inputPosition = ""
lang = ""
